[theme]
primaryColor="#ff4b4e"
backgroundColor="#f2e8d8"
secondaryBackgroundColor="#c8b394"
textColor="#141a4e"
font="serif"
                                                                                                                             